services:
  mon-serveur:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "8080:80"
      - "81:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  mon-site:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html

